# Dale un nombre único a tu aplicación en Fly.io
app = "chatbot-ia-backend"
primary_region = "scl"  # ¡Región de Santiago, Chile! Ideal para ti.

# Sección de construcción: le dice a Fly.io cómo construir tu imagen
[build]
  # Ruta a tu Dockerfile desde la raíz del proyecto
  dockerfile = "backend/Dockerfile"

# Sección del servicio web: cómo se expone tu app a internet
[http_service]
  internal_port = 8000  # El puerto en el que corre Gunicorn DENTRO del contenedor
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

# Define el tamaño de la máquina virtual (el plan gratuito)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256