services:
  - type: web
    name: backend
    env: python
    region: oregon
    plan: free
    buildFilter:
      paths:
        - "backend/**"
    buildCommand: "pip install -r backend/requirements.txt && python backend/manage.py collectstatic --noinput"
    startCommand: "gunicorn config.wsgi:application --pythonpath backend"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_URL}
      - key: WEB_CONCURRENCY
        value: 4
databases:
  - name: db
    databaseName: db
    plan: free