services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/dockerfile
    region: oregon
    plan: free
    buildFilter:
      paths:
        - "backend/**"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ${RENDER_EXTERNAL_URL}
      - key: WEB_CONCURRENCY
        value: 4
databases:
  - name: db
    databaseName: db
    plan: free