FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Directorio de trabajo del contenedor
WORKDIR /app

# Instalación de dependencias
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copiar el resto del código de la aplicación
COPY . .

CMD python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000