# Generated by Django 5.2.6 on 2025-11-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_emotion_anger_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='needs_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='support_level',
            field=models.CharField(blank=True, choices=[('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='support_resources',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='support_resources_offered',
            field=models.BooleanField(default=False),
        ),
    ]
