# Generated by Django 5.2.6 on 2025-11-10 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_needs_support_message_support_level_and_more'),
        ('users', '0003_alter_customuser_role_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEmotionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_emotion', models.CharField(max_length=50)),
                ('emotion_ratio', models.FloatField(help_text='Porcentaje de mensajes donde predominó la emoción que disparó la sugerencia.')),
                ('time_window_days', models.PositiveSmallIntegerField(default=7)),
                ('stats_snapshot', models.JSONField(default=dict, help_text='Métricas agregadas usadas para la recomendación.')),
                ('overview', models.TextField(help_text='Resumen pedagógico generado por la IA.')),
                ('suggestions', models.JSONField(help_text='Lista de sugerencias o actividades recomendadas.')),
                ('disclaimer', models.CharField(default='Estas recomendaciones son educativas y no reemplazan la atención psicológica profesional.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_recommendations', to='users.course')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_emotion_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
