# Generated by Django 5.2.6 on 2025-09-27 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
