# Generated by Django 5.2.6 on 2025-11-02 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_customuser_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Estudiante'), ('teacher', 'Profesor'), ('admin', 'Administrador')], default='student', max_length=10),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del curso (ej: Matemáticas 3°A)', max_length=200)),
                ('code', models.CharField(help_text='Código único del curso (ej: MAT3A-2025)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción del curso')),
                ('start_date', models.DateField(help_text='Fecha de inicio del curso')),
                ('end_date', models.DateField(help_text='Fecha de finalización del curso')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el curso está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, help_text='Estudiantes inscritos en el curso', limit_choices_to={'role': 'student'}, related_name='courses_enrolled', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, help_text='Profesor asignado', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-start_date', 'name'],
            },
        ),
    ]
